In [ ]:
import cv2
import numpy as np
from keras.models import model_from_json


emotion_dict = {0: "Angry", 1: "Disgusted", 2: "Fearful", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprised"}

# load json and create model
json_file = open('model/emotion_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
emotion_model = model_from_json(loaded_model_json)

# load weights into new model
emotion_model.load_weights("model/emotion_model.h5")
print("Loaded model from disk")

# start the webcam feed
#cap = cv2.VideoCapture(0)

# pass here your video path
# you may download one from here : https://www.pexels.com/video/three-girls-laughing-5273028/
cap = cv2.VideoCapture("C:\\Users\\91756\\Downloads\\pexels-gabby-k-5273028.mp4")

while True:
    # Find haar cascade to draw bounding box around face
    ret, frame = cap.read()
    
    print(frame)
    if ret is None:
        print('Wrong path:', path)
    else:    
        frame = cv2.resize(frame, (1280, 720))
    
    

    face_detector = cv2.CascadeClassifier('haarcascades/haarcascade_frontalface_default.xml')
    gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # detect faces available on camera
    num_faces = face_detector.detectMultiScale(gray_frame, scaleFactor=1.3, minNeighbors=5)

    # take each face available on the camera and Preprocess it
    for (x, y, w, h) in num_faces:
        cv2.rectangle(frame, (x, y-50), (x+w, y+h+10), (0, 255, 0), 4)
        roi_gray_frame = gray_frame[y:y + h, x:x + w]
        cropped_img = np.expand_dims(np.expand_dims(cv2.resize(roi_gray_frame, (48, 48)), -1), 0)

        # predict the emotions
        emotion_prediction = emotion_model.predict(cropped_img)
        maxindex = int(np.argmax(emotion_prediction))
        cv2.putText(frame, emotion_dict[maxindex], (x+5, y-20), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)

    cv2.imshow('Emotion Detection', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


C:\Users\91756\anaconda\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Loaded model from disk
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 207 209]
  [208 207 209]
  [208 207 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 207 209]
  [208 207 209]
  [208 207 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 207 209]
  [208 207 209]
  [208 207 209]]

 ...

 [[107 103  91]
  [106 102  90]
  [107 103  91]
  ...
  [171 173 175]
  [171 173 175]
  [171 173 175]]

 [[106 102  90]
  [107 103  91]
  [108 104  92]
  ...
  [171 173 175]
  [171 173 175]
  [171 173 175]]

 [[107 103  91]
  [109 105  93]
  [109 105  93]
  ...
  [171 173 175]
  [171 173 175]
  [171 173 175]]]
1/1 [==============================] - 0s 22ms/step
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
 

1/1 [==============================] - 0s 31ms/step
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 ...

 [[ 99  97  80]
  [102 100  83]
  [103 102  82]
  ...
  [165 167 169]
  [161 163 165]
  [160 162 164]]

 [[100  98  81]
  [102 100  83]
  [102 101  81]
  ...
  [165 167 169]
  [161 163 165]
  [160 162 164]]

 [[100  98  81]
  [101  99  82]
  [101 100  80]
  ...
  [165 167 169]
  [161 163 165]
  [160 162 164]]]
1/1 [==============================] - 0s 25ms/step
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [208 208 208]
  [208 208 208]
  [208 208 208]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [2

1/1 [==============================] - 0s 38ms/step
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 ...

 [[ 59  87 131]
  [ 59  87 131]
  [ 61  89 133]
  ...
  [169 171 173]
  [169 171 173]
  [169 171 173]]

 [[ 59  87 131]
  [ 59  87 131]
  [ 61  89 133]
  ...
  [169 171 173]
  [169 171 173]
  [169 171 173]]

 [[ 59  87 131]
  [ 59  87 131]
  [ 61  89 133]
  ...
  [169 171 173]
  [169 171 173]
  [169 171 173]]]
1/1 [==============================] - 0s 29ms/step
[[[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [209 209 209]
  [209 209 209]
  [209 209 209]]

 [[189 191 193]
  [189 191 193]
  [189 191 193]
  ...
  [2